### ISSUE TITLE
Issues with GitLab 6.x after upgrading to Mac OS X 10.10.5

### ISSUE THREAD

**Issue by corydorning** [WebEntity/Installation-guide-for-GitLab-on-OS-X#62]
I recently upgraded from 10.8 to 10.10 and it hosed our entire GitLab setup on our Mac Mini Server. I walked back through the GitLab 6.x guide and managed to get everything setup again under 10.10. After stumbling through various issues, I got it to were it says GitLab is running.

However, when I try and pull it up in the browser, I get a 502 Proxy Error:
```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /.

Reason: Error reading from remote server
```

When I run the command:
```
sudo -u git /Users/git/gitlab-shell/bin/check
```

It returns:
```
Check GitLab API access: FAILED. code: 302
```

**Anyone have any ideas as to what might be causing this?**

**Comment by corydorning** [comment]
Uploading my conf files isn't working so here they are...

**config.yml**
```
# GitLab user. git by default
user: git

# Url to gitlab instance. Used for api calls. Should end with a slash.
gitlab_url: "http://mcws110160016.info53.com"

http_settings:
#  user: someone
#  password: somepass
#  ca_file: /etc/ssl/cert.pem
#  ca_path: /etc/pki/tls/certs
  self_signed_cert: false

# Repositories path
# Give the canonicalized absolute pathname,
# REPOS_PATH MUST NOT CONTAIN ANY SYMLINK!!!
# Check twice that none of the components is a symlink, including "/home".
repos_path: "/Users/git/repositories"

# File used as authorized_keys for gitlab user
auth_file: "/Users/git/.ssh/authorized_keys"

# Redis settings used for pushing commit notices to gitlab
redis:
  bin: /usr/local/bin/redis-cli
  host: 127.0.0.1
  port: 6379
  # socket: /tmp/redis.socket # Only define this if you want to use sockets
  namespace: resque:gitlab

# Log file.
# Default is gitlab-shell.log in the root directory.
# log_file: "/Users/git/gitlab-shell/gitlab-shell.log"

# Log level. INFO by default
log_level: INFO

# Audit usernames.
# Set to true to see real usernames in the logs instead of key ids, which is easier to follow, but
# incurs an extra API call on every gitlab-shell command.
audit_usernames: false
```
